---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-stone-prd-rh01_object_too_large_for_cache
