---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-KAR-746_upgrade_loki_stack_components
