---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-stone-stg-rh01_unscheduled_vector_pods
